// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/confirmation', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/confirmation')
  })

  test('searching — renders without error', async ({ screen }) => {
    await screen.switchState('searching')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('found — renders without error', async ({ screen }) => {
    await screen.switchState('found')
    await expect(screen.frame).not.toBeEmpty()
  })
})
