// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/location', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/location')
  })

  test('location:initial — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Location', 'initial')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('location:search-results — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Location', 'search-results')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('location:selected — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Location', 'selected')
    await expect(screen.frame).not.toBeEmpty()
  })
})
