// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/location', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/location')
  })

  test('initial — renders without error', async ({ screen }) => {
    await screen.switchState('initial')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('search-results — renders without error', async ({ screen }) => {
    await screen.switchState('search-results')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('selected — renders without error', async ({ screen }) => {
    await screen.switchState('selected')
    await expect(screen.frame).not.toBeEmpty()
  })
})
