// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/doctor', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/doctor')
  })

  test('doctor:browsing — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Doctor', 'browsing')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('doctor:selected — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Doctor', 'selected')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('doctor:specialty-drawer — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Doctor', 'specialty-drawer')
    await expect(screen.frame).not.toBeEmpty()
  })
})
