// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/search', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/search')
  })

  test('search:empty — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Search', 'empty')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('search:partial — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Search', 'partial')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('search:ready — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Search', 'ready')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('search:loading — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Search', 'loading')
    await expect(screen.frame).not.toBeEmpty()
  })
})
