// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/confirmation', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/confirmation')
  })

  test('confirmation:searching — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Confirmation', 'searching')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('confirmation:found — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Confirmation', 'found')
    await expect(screen.frame).not.toBeEmpty()
  })
})
