// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/type', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/type')
  })

  test('acute — renders without error', async ({ screen }) => {
    await screen.switchState('acute')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('prevention — renders without error', async ({ screen }) => {
    await screen.switchState('prevention')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('follow-up — renders without error', async ({ screen }) => {
    await screen.switchState('follow-up')
    await expect(screen.frame).not.toBeEmpty()
  })
})
