import type { ViewTree } from '../analyzer/types.js'
import { formatValue } from './format-utils.js'

export function generateViewFileContent(viewTree: ViewTree): string {
  const lines: string[] = []
  lines.push('// Auto-generated by @preview-tool/cli — do not edit manually')
  lines.push('')
  lines.push(`export const view = ${formatValue(viewTree, 0)} as const`)
  lines.push('')
  return lines.join('\n')
}
