import type { ScreenAnalysis } from '../analyzer/types.js'

/**
 * Generates TypeScript file content for a screen's mock data.
 * Outputs a file with `meta`, `regions`, and `flows` exports.
 */
export function generateMockFileContent(analysis: ScreenAnalysis): string {
  const { screen, regions, flows } = analysis
  const lines: string[] = []

  lines.push('// Auto-generated by @preview-tool/cli — do not edit manually')
  lines.push('')

  // Meta export
  lines.push('export const meta = {')
  lines.push(`  route: ${JSON.stringify(screen.route)},`)
  lines.push(`  pattern: ${JSON.stringify(screen.pattern)},`)
  lines.push(`  filePath: ${JSON.stringify(screen.filePath)},`)
  lines.push('} as const')
  lines.push('')

  // Regions export
  lines.push('export const regions = {')
  for (const [key, region] of Object.entries(regions)) {
    lines.push(`  ${JSON.stringify(key)}: {`)
    lines.push(`    label: ${JSON.stringify(region.label)},`)
    lines.push(`    defaultState: ${JSON.stringify(region.defaultState)},`)
    lines.push(`    states: ${formatValue(region.states, 4)},`)

    if (region.isList) {
      lines.push(`    isList: true,`)
      lines.push(`    defaultCount: ${region.defaultCount ?? 3},`)
      if (region.mockItems) {
        lines.push(`    mockItems: ${formatValue(region.mockItems, 4)},`)
      }
    }

    lines.push('  },')
  }
  lines.push('} as const')
  lines.push('')

  // Flows export
  lines.push('export const flows = [')
  for (const flow of flows) {
    lines.push(`  {`)
    lines.push(`    trigger: ${JSON.stringify(flow.trigger)},`)
    if (flow.navigate) {
      lines.push(`    navigate: ${JSON.stringify(flow.navigate)},`)
    }
    if (flow.transition) {
      lines.push(`    transition: ${formatValue(flow.transition, 4)},`)
    }
    if (flow.delay) {
      lines.push(`    delay: ${flow.delay},`)
    }
    if (flow.then) {
      lines.push(`    then: ${formatValue(flow.then, 4)},`)
    }
    lines.push(`  },`)
  }
  lines.push('] as const')
  lines.push('')

  return lines.join('\n')
}

function formatValue(value: unknown, indent: number): string {
  const json = JSON.stringify(value, null, 2)
  // Re-indent to match current context
  const padding = ' '.repeat(indent)
  return json
    .split('\n')
    .map((line, i) => (i === 0 ? line : padding + line))
    .join('\n')
}
