import type { ControllerOutput } from '../analyzer/types.js'
import { formatValue } from './format-utils.js'

export function generateControllerFileContent(controller: ControllerOutput): string {
  const lines: string[] = []
  lines.push('// Auto-generated by @preview-tool/cli — do not edit manually')
  lines.push('')
  lines.push(`export const flows = ${formatValue(controller.flows, 0)} as const`)
  lines.push('')
  lines.push(`export const componentStates = ${formatValue(controller.componentStates, 0)} as const`)
  lines.push('')
  lines.push(`export const journeys = ${formatValue(controller.journeys, 0)} as const`)
  lines.push('')
  return lines.join('\n')
}
