import type { ScreenStateMachine, StateNode } from '../analyzer/types.js'

/**
 * Serializes a ScreenStateMachine to TypeScript source code for a scenario file.
 * Exports:
 *   - scenarios: Scenario[]   — one entry per state node
 *   - defaultScenario: string — id of the default scenario
 *
 * Never throws — returns a minimal valid file on any error.
 */
export function generateScenarios(machine: ScreenStateMachine): string {
  try {
    const defaultScenario = pickDefault(machine)
    const scenarioObjects = machine.states.map(state => serializeScenario(state))
    const scenariosArray = `[\n${scenarioObjects.map(s => indent(s, 2)).join(',\n')},\n]`

    return [
      `// Auto-generated by preview-tool — do not edit`,
      ``,
      `import type { Scenario } from '@preview-tool/runtime'`,
      ``,
      `export const scenarios: Scenario[] = ${scenariosArray}`,
      ``,
      `export const defaultScenario = ${JSON.stringify(defaultScenario)}`,
      ``,
    ].join('\n')
  } catch {
    return fallbackOutput()
  }
}

function pickDefault(machine: ScreenStateMachine): string {
  if (machine.states.some(s => s.id === 'success')) return 'success'
  if (machine.states.some(s => s.id === 'done')) return 'done'
  return machine.initialState || machine.states[0]?.id || 'default'
}

function serializeScenario(state: StateNode): string {
  const mockDataStr = serializeMockData(state.mockData)
  return [
    `{`,
    `  id: ${JSON.stringify(state.id)},`,
    `  label: ${JSON.stringify(state.label)},`,
    `  mockData: ${mockDataStr},`,
    `  source: ${JSON.stringify(state.source)},`,
    `}`,
  ].join('\n')
}

function serializeMockData(data: Record<string, unknown>): string {
  if (Object.keys(data).length === 0) return '{}'
  const entries = Object.entries(data)
    .map(([k, v]) => `  ${k}: ${serializeValue(v)}`)
    .join(',\n')
  return `{\n${entries},\n}`
}

function serializeValue(value: unknown): string {
  if (value === undefined) return 'undefined'
  if (value === null) return 'null'
  if (typeof value === 'boolean' || typeof value === 'number') return String(value)
  if (typeof value === 'string') return JSON.stringify(value)
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    return `[${value.map(serializeValue).join(', ')}]`
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .map(([k, v]) => `${k}: ${serializeValue(v)}`)
      .join(', ')
    return `{ ${entries} }`
  }
  return JSON.stringify(value)
}

function indent(text: string, spaces: number): string {
  const pad = ' '.repeat(spaces)
  return text.split('\n').map(line => (line ? pad + line : line)).join('\n')
}

function fallbackOutput(): string {
  return [
    `// Auto-generated by preview-tool — do not edit`,
    ``,
    `import type { Scenario } from '@preview-tool/runtime'`,
    ``,
    `export const scenarios: Scenario[] = [{ id: 'default', label: 'Default', mockData: {}, source: 'unknown' }]`,
    ``,
    `export const defaultScenario = 'default'`,
    ``,
  ].join('\n')
}
