import type { ModelOutput } from '../analyzer/types.js'

export function generateModelFileContent(
  model: ModelOutput,
  meta: { route: string; pattern: string; filePath: string }
): string {
  const lines: string[] = []
  lines.push('// Auto-generated by @preview-tool/cli — do not edit manually')
  lines.push('')
  lines.push('export const meta = {')
  lines.push(`  route: ${JSON.stringify(meta.route)},`)
  lines.push(`  pattern: ${JSON.stringify(meta.pattern)},`)
  lines.push(`  filePath: ${JSON.stringify(meta.filePath)},`)
  lines.push('} as const')
  lines.push('')
  lines.push(`export const regions = ${formatValue(model.regions, 0)} as const`)
  lines.push('')
  return lines.join('\n')
}

function formatValue(value: unknown, indent: number): string {
  const json = JSON.stringify(value, null, 2)
  const padding = ' '.repeat(indent)
  return json
    .split('\n')
    .map((line, i) => (i === 0 ? line : padding + line))
    .join('\n')
}
