import { relative, dirname, posix } from 'node:path'
import type { DiscoveredScreen } from '../analyzer/types.js'

/**
 * Generates TypeScript adapter file content.
 * The adapter imports the screen component and its mock data,
 * then re-exports them in the shape expected by PreviewShell.
 */
export function generateAdapterFileContent(
  screen: DiscoveredScreen,
  adapterPath: string,
  mockPath: string,
  hostCwd: string
): string {
  // Calculate relative paths from the adapter file to the screen and mock
  const adapterDir = dirname(adapterPath)
  const relativeToScreen = toRelativeImport(adapterDir, screen.filePath)
  const relativeToMock = toRelativeImport(adapterDir, mockPath)

  const lines: string[] = []

  lines.push('// Auto-generated by @preview-tool/cli — do not edit manually')
  lines.push(`import Screen from '${relativeToScreen}'`)
  lines.push(`import { meta, regions, flows } from '${relativeToMock}'`)
  lines.push('')
  lines.push('export default Screen')
  lines.push('export { meta, regions, flows }')
  lines.push('')

  return lines.join('\n')
}

/**
 * Converts an absolute target path to a relative import from a source directory.
 * Always uses posix separators and ensures a leading './'
 */
function toRelativeImport(fromDir: string, toFile: string): string {
  let rel = relative(fromDir, toFile)
  // Convert to posix
  rel = rel.split('\\').join('/')
  // Strip .ts/.tsx extension for import
  rel = rel.replace(/\.(tsx?)$/, '')
  // Ensure relative prefix
  if (!rel.startsWith('.')) {
    rel = './' + rel
  }
  return rel
}
