import type { ControllerOutput } from '../analyzer/types.js'

export function generateControllerFileContent(controller: ControllerOutput): string {
  const lines: string[] = []
  lines.push('// Auto-generated by @preview-tool/cli — do not edit manually')
  lines.push('')
  lines.push(`export const flows = ${formatValue(controller.flows, 0)} as const`)
  lines.push('')
  lines.push(`export const componentStates = ${formatValue(controller.componentStates, 0)} as const`)
  lines.push('')
  lines.push(`export const journeys = ${formatValue(controller.journeys, 0)} as const`)
  lines.push('')
  return lines.join('\n')
}

function formatValue(value: unknown, indent: number): string {
  const json = JSON.stringify(value, null, 2)
  const padding = ' '.repeat(indent)
  return json
    .split('\n')
    .map((line, i) => (i === 0 ? line : padding + line))
    .join('\n')
}
