import { writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'
import { PREVIEW_DIR } from '../lib/config.js'
import type { PreviewConfig } from '../lib/config.js'

/**
 * Generates the index.html and main.tsx entry files in the .preview directory.
 * These files bootstrap the PreviewShell from @preview-tool/runtime.
 */
export async function generateEntryFiles(
  cwd: string,
  config: PreviewConfig
): Promise<void> {
  const previewDir = join(cwd, PREVIEW_DIR)
  await mkdir(previewDir, { recursive: true })

  await writeFile(
    join(previewDir, 'index.html'),
    generateIndexHtml(config.title),
    'utf-8'
  )

  await writeFile(
    join(previewDir, 'main.tsx'),
    generateMainTsx(),
    'utf-8'
  )
}

function generateIndexHtml(title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(title)}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./main.tsx"></script>
  </body>
</html>
`
}

function generateMainTsx(): string {
  return `// Auto-generated by @preview-tool/cli — do not edit manually
import React from 'react'
import { createRoot } from 'react-dom/client'
import { PreviewShell, registerScreens } from '@preview-tool/runtime'
import type { ScreenEntry } from '@preview-tool/runtime'

// Auto-discover adapters via import.meta.glob
const adapterModules = import.meta.glob('./adapters/*.adapter.ts')
const mockModules = import.meta.glob('./mocks/*.mock.ts', { eager: true }) as Record<
  string,
  { meta: { route: string }; regions: Record<string, unknown>; flows: readonly unknown[] }
>

// Build screen entries from discovered adapters + mocks
const entries: ScreenEntry[] = []

for (const [adapterPath, importFn] of Object.entries(adapterModules)) {
  // Derive mock path from adapter path
  const fileName = adapterPath.split('/').pop()?.replace('.adapter.ts', '') ?? ''
  const mockPath = \`./mocks/\${fileName}.mock.ts\`
  const mock = mockModules[mockPath]

  if (!mock) continue

  entries.push({
    route: mock.meta.route,
    module: importFn as () => Promise<{ default: React.ComponentType<{ data: unknown; flags?: Record<string, boolean> }> }>,
    regions: mock.regions as ScreenEntry['regions'],
  })
}

// Register and render
registerScreens(entries)

const root = document.getElementById('root')
if (root) {
  createRoot(root).render(
    <React.StrictMode>
      <PreviewShell />
    </React.StrictMode>
  )
}
`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
