import { writeFile, mkdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join, dirname, relative } from 'node:path'
import { createRequire } from 'node:module'
import { PREVIEW_DIR } from '../lib/config.js'
import type { PreviewConfig } from '../lib/config.js'

/**
 * Resolve the @preview-tool/runtime package root.
 */
function resolveRuntimePath(): string {
  const require = createRequire(import.meta.url)
  const runtimeEntry = require.resolve('@preview-tool/runtime')
  let dir = dirname(runtimeEntry)
  for (let i = 0; i < 5; i++) {
    try {
      require.resolve(join(dir, 'package.json'))
      return dir
    } catch {
      dir = dirname(dir)
    }
  }
  return dirname(runtimeEntry)
}

/**
 * Generates the index.html, main.tsx, and preview.css entry files.
 */
export async function generateEntryFiles(
  cwd: string,
  config: PreviewConfig
): Promise<void> {
  const previewDir = join(cwd, PREVIEW_DIR)
  await mkdir(previewDir, { recursive: true })

  await writeFile(
    join(previewDir, 'index.html'),
    generateIndexHtml(config.title),
    'utf-8'
  )

  // Detect host project CSS file
  const cssFiles = ['src/index.css', 'src/App.css', 'src/styles/globals.css']
  let hostCssPath: string | null = null
  for (const cssFile of cssFiles) {
    if (existsSync(join(cwd, cssFile))) {
      hostCssPath = cssFile
      break
    }
  }

  // Generate a wrapper CSS that imports host CSS + adds @source for runtime
  const runtimeRoot = resolveRuntimePath()
  const runtimeSrcRelative = relative(previewDir, join(runtimeRoot, 'src'))
  const hostSrcRelative = relative(previewDir, join(cwd, 'src'))

  await writeFile(
    join(previewDir, 'preview.css'),
    generatePreviewCss(hostCssPath, hostSrcRelative, runtimeSrcRelative),
    'utf-8'
  )

  await writeFile(
    join(previewDir, 'main.tsx'),
    generateMainTsx(),
    'utf-8'
  )
}

function generateIndexHtml(title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(title)}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./main.tsx"></script>
  </body>
</html>
`
}

function generatePreviewCss(
  hostCssPath: string | null,
  hostSrcRelative: string,
  runtimeSrcRelative: string
): string {
  const lines: string[] = [
    '/* Auto-generated by @preview-tool/cli — do not edit manually */',
  ]

  if (hostCssPath) {
    // Import the host project's CSS (which includes @import "tailwindcss")
    lines.push(`@import "${hostSrcRelative}/${hostCssPath.replace('src/', '')}";`)
  }

  // Tell Tailwind CSS v4 to also scan the runtime package and host src for classes
  lines.push(`@source "${runtimeSrcRelative}";`)
  lines.push(`@source "${hostSrcRelative}";`)

  return lines.join('\n') + '\n'
}

function generateMainTsx(): string {
  return `// Auto-generated by @preview-tool/cli — do not edit manually
import React from 'react'
import { createRoot } from 'react-dom/client'
import { PreviewShell } from '@preview-tool/runtime'
import { screens } from './screens.ts'
import './preview.css'

const root = document.getElementById('root')
if (root) {
  createRoot(root).render(
    <React.StrictMode>
      <PreviewShell screens={screens} title="Preview Tool" />
    </React.StrictMode>
  )
}
`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
