// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/appointments', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/appointments')
  })

  test('loaded — renders without error', async ({ screen }) => {
    await screen.switchState('loaded')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('empty — renders without error', async ({ screen }) => {
    await screen.switchState('empty')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('loading — renders without error', async ({ screen }) => {
    await screen.switchState('loading')
    await expect(screen.frame).not.toBeEmpty()
  })
})
