// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../_test-helpers/fixtures'

test.describe('hello-world', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('hello-world')
  })

  test('items:loading — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Items', 'loading')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('items:empty — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Items', 'empty')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('items:populated — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Items', 'populated')
    await expect(screen.frame).not.toBeEmpty()
  })
})
