// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('prescription/confirmation', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('prescription/confirmation')
  })

  test('confirmation:review-pickup — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Confirmation', 'review-pickup')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('confirmation:review-delivery — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Confirmation', 'review-delivery')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('confirmation:submitting — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Confirmation', 'submitting')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('confirmation:success-pickup — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Confirmation', 'success-pickup')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('confirmation:success-delivery — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Confirmation', 'success-delivery')
    await expect(screen.frame).not.toBeEmpty()
  })
})
