// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('prescription/scan', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('prescription/scan')
  })

  test('scan:idle — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Scan', 'idle')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('scan:scanning — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Scan', 'scanning')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('scan:success — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Scan', 'success')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('scan:error — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Scan', 'error')
    await expect(screen.frame).not.toBeEmpty()
  })
})
