// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('prescription/scan', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('prescription/scan')
  })

  test('idle — renders without error', async ({ screen }) => {
    await screen.switchState('idle')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('scanning — renders without error', async ({ screen }) => {
    await screen.switchState('scanning')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('success — renders without error', async ({ screen }) => {
    await screen.switchState('success')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('error — renders without error', async ({ screen }) => {
    await screen.switchState('error')
    await expect(screen.frame).not.toBeEmpty()
  })
})
