// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/patient', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/patient')
  })

  test('self — renders without error', async ({ screen }) => {
    await screen.switchState('self')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('family — renders without error', async ({ screen }) => {
    await screen.switchState('family')
    await expect(screen.frame).not.toBeEmpty()
  })
})
