// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/patient', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/patient')
  })

  test('patient:self — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Patient', 'self')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('patient:family — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Patient', 'family')
    await expect(screen.frame).not.toBeEmpty()
  })
})
