// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../_test-helpers/fixtures'

test.describe('profile', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('profile')
  })

  test('user:loading — renders without error', async ({ screen }) => {
    await screen.switchRegionState('User Info', 'loading')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('user:populated — renders without error', async ({ screen }) => {
    await screen.switchRegionState('User Info', 'populated')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('insurances:loading — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Insurance', 'loading')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('insurances:empty — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Insurance', 'empty')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('insurances:populated — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Insurance', 'populated')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('familyMembers:loading — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Family Members', 'loading')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('familyMembers:empty — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Family Members', 'empty')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('familyMembers:populated — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Family Members', 'populated')
    await expect(screen.frame).not.toBeEmpty()
  })
})
