// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/appointments', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/appointments')
  })

  test('appointments:loaded — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Appointments', 'loaded')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('appointments:empty — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Appointments', 'empty')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('appointments:loading — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Appointments', 'loading')
    await expect(screen.frame).not.toBeEmpty()
  })
})
