// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/type', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/type')
  })

  test('type:acute — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Type', 'acute')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('type:prevention — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Type', 'prevention')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('type:follow-up — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Type', 'follow-up')
    await expect(screen.frame).not.toBeEmpty()
  })
})
