// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../_test-helpers/fixtures'

test.describe('login', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('login')
  })

  test('idle — renders without error', async ({ screen }) => {
    await screen.switchState('idle')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('filling — renders without error', async ({ screen }) => {
    await screen.switchState('filling')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('error — renders without error', async ({ screen }) => {
    await screen.switchState('error')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('success — renders without error', async ({ screen }) => {
    await screen.switchState('success')
    await expect(screen.frame).not.toBeEmpty()
  })
})
