// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../_test-helpers/fixtures'

test.describe('login', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('login')
  })

  test('login:idle — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Login', 'idle')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('login:filling — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Login', 'filling')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('login:error — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Login', 'error')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('login:success — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Login', 'success')
    await expect(screen.frame).not.toBeEmpty()
  })
})
