// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/doctor', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/doctor')
  })

  test('browsing — renders without error', async ({ screen }) => {
    await screen.switchState('browsing')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('selected — renders without error', async ({ screen }) => {
    await screen.switchState('selected')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('specialty-drawer — renders without error', async ({ screen }) => {
    await screen.switchState('specialty-drawer')
    await expect(screen.frame).not.toBeEmpty()
  })
})
