// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('prescription/list', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('prescription/list')
  })

  test('prescriptions:loading — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Prescriptions', 'loading')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('prescriptions:empty — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Prescriptions', 'empty')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('prescriptions:populated — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Prescriptions', 'populated')
    await expect(screen.frame).not.toBeEmpty()
  })
})
