// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/time-slots', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/time-slots')
  })

  test('timeSlots:all-selected — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Time Slots', 'all-selected')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('timeSlots:partial — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Time Slots', 'partial')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('timeSlots:minimal — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Time Slots', 'minimal')
    await expect(screen.frame).not.toBeEmpty()
  })
})
