// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('booking/time-slots', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('booking/time-slots')
  })

  test('all-selected — renders without error', async ({ screen }) => {
    await screen.switchState('all-selected')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('partial — renders without error', async ({ screen }) => {
    await screen.switchState('partial')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('minimal — renders without error', async ({ screen }) => {
    await screen.switchState('minimal')
    await expect(screen.frame).not.toBeEmpty()
  })
})
