// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../_test-helpers/fixtures'

test.describe('hello', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('hello')
  })

  test('hello:default — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Hello', 'default')
    await expect(screen.frame).not.toBeEmpty()
  })
})
