// Auto-generated by scripts/generate-screen-tests.mjs — do not edit manually

import { test, expect } from '../../_test-helpers/fixtures'

test.describe('prescription/delivery', () => {
  test.beforeEach(async ({ screen }) => {
    await screen.select('prescription/delivery')
  })

  test('delivery:none-selected — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Delivery', 'none-selected')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('delivery:home-delivery-prefilled — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Delivery', 'home-delivery-prefilled')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('delivery:home-delivery-empty — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Delivery', 'home-delivery-empty')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('delivery:apotheke-loading — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Delivery', 'apotheke-loading')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('delivery:apotheke-list — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Delivery', 'apotheke-list')
    await expect(screen.frame).not.toBeEmpty()
  })

  test('delivery:apotheke-selected — renders without error', async ({ screen }) => {
    await screen.switchRegionState('Delivery', 'apotheke-selected')
    await expect(screen.frame).not.toBeEmpty()
  })
})
